/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplo5;

import javax.swing.JOptionPane;

public class Exemplo5 extends javax.swing.JFrame {

    /**
     * Creates new form Exemplo5
     */
    public Exemplo5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttGroupSexo = new javax.swing.ButtonGroup();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        rBttMasculino = new javax.swing.JRadioButton();
        rBttFeminino = new javax.swing.JRadioButton();
        rBttNaoBinario = new javax.swing.JRadioButton();
        cbC = new javax.swing.JCheckBox();
        cbPHP = new javax.swing.JCheckBox();
        cbCSharp = new javax.swing.JCheckBox();
        cbJS = new javax.swing.JCheckBox();
        cbJava = new javax.swing.JCheckBox();
        cbHtml = new javax.swing.JCheckBox();
        lblLinguagem = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblEscolaridade = new javax.swing.JLabel();
        bttGravar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setText("Nome");

        lblEmail.setText("Email");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        bttGroupSexo.add(rBttMasculino);
        rBttMasculino.setText("Masculino");
        rBttMasculino.setToolTipText("");

        bttGroupSexo.add(rBttFeminino);
        rBttFeminino.setText("Feminino");

        bttGroupSexo.add(rBttNaoBinario);
        rBttNaoBinario.setText("Não Binario");

        cbC.setText("C");

        cbPHP.setText("PHP");

        cbCSharp.setText("C#");

        cbJS.setText("JavaScript");

        cbJava.setText("Java");

        cbHtml.setText("Html/css");

        lblLinguagem.setText("Linguagens:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medio", "Graduação", "Mestrado", "Doutorado" }));

        lblEscolaridade.setText("Escolaridade");

        bttGravar.setText("Gravar");
        bttGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttGravarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        txtAreaResultado.setEditable(false);
        txtAreaResultado.setColumns(20);
        txtAreaResultado.setRows(5);
        jScrollPane1.setViewportView(txtAreaResultado);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome)
                    .addComponent(lblEmail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtEmail)
                        .addComponent(txtNome)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rBttMasculino)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(lblEscolaridade)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rBttFeminino)
                                    .addGap(18, 18, 18)
                                    .addComponent(rBttNaoBinario))))
                        .addComponent(bttGravar, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblLinguagem)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbC)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbPHP)
                                    .addGap(30, 30, 30))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbCSharp)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbJS)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbJava)
                                .addGap(10, 10, 10)
                                .addComponent(cbHtml)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBttMasculino)
                    .addComponent(rBttFeminino)
                    .addComponent(rBttNaoBinario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbC)
                    .addComponent(cbPHP)
                    .addComponent(lblLinguagem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCSharp)
                    .addComponent(cbJS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbJava)
                    .addComponent(cbHtml))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEscolaridade))
                .addGap(17, 17, 17)
                .addComponent(bttGravar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void bttGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttGravarActionPerformed
        txtAreaResultado.setText(" ");
        txtAreaResultado.append("Nome: "+txtNome.getText());
        txtAreaResultado.append("\nEmail: "+txtEmail.getText());
        
        String rbtTexto = new String();
        
        if (rBttNaoBinario.isSelected()==true){
            rbtTexto = rBttNaoBinario.getText();
        }else if (rBttMasculino.isSelected()==true){
            rbtTexto=rBttMasculino.getText();
        }else if (rBttFeminino.isSelected()==true){
            rbtTexto = rBttFeminino.getText();
        }
        txtAreaResultado.append("\nGenero: "+rbtTexto);
        
        String cbTexto = new String();
        
        if(cbC.isSelected()==true){
            cbTexto+=cbC.getText()+", ";
        }
        if(cbCSharp.isSelected()==true){
            cbTexto+=cbCSharp.getText()+", ";
        }
        if(cbPHP.isSelected()==true){
            cbTexto+=cbPHP.getText()+", ";
        }
        if(cbJS.isSelected()==true){
            cbTexto+=cbJS.getText()+", ";
        }
        if(cbJava.isSelected()==true){
            cbTexto+=cbJava.getText()+", ";
        }
        if(cbHtml.isSelected()==true){
            cbTexto+=cbHtml.getText()+", ";
        }
        txtAreaResultado.append("\nLinguagens: "+cbTexto);
        
        txtAreaResultado.append("\nEscolaridade: "+jComboBox1.getSelectedItem());
        
    }//GEN-LAST:event_bttGravarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exemplo5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exemplo5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exemplo5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exemplo5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exemplo5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttGravar;
    private javax.swing.ButtonGroup bttGroupSexo;
    private javax.swing.JCheckBox cbC;
    private javax.swing.JCheckBox cbCSharp;
    private javax.swing.JCheckBox cbHtml;
    private javax.swing.JCheckBox cbJS;
    private javax.swing.JCheckBox cbJava;
    private javax.swing.JCheckBox cbPHP;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEscolaridade;
    private javax.swing.JLabel lblLinguagem;
    private javax.swing.JLabel lblNome;
    private javax.swing.JRadioButton rBttFeminino;
    private javax.swing.JRadioButton rBttMasculino;
    private javax.swing.JRadioButton rBttNaoBinario;
    private javax.swing.JTextArea txtAreaResultado;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
